# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='data_type',
            field=models.CharField(choices=[(b'news', '\u041d\u043e\u0432\u043e\u0441\u0442\u0438'), (b'articles', '\u0421\u0442\u0430\u0442\u044c\u0438')], max_length=10, verbose_name='\u0442\u0438\u043f \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438'),
        ),
    ]
