# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0430\u0439\u0442\u0430')),
                ('main_title', models.CharField(max_length=255, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u043e\u0439')),
                ('main_preview', tinymce.models.HTMLField(verbose_name='\u043a\u0440\u0430\u0442\u043a\u0438\u0439 \u0442\u0435\u043a\u0441\u0442 \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u043e\u0439')),
                ('main_text', tinymce.models.HTMLField(verbose_name='\u0442\u0435\u043a\u0441\u0442 \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u043e\u0439')),
                ('phone1', models.CharField(blank=True, max_length=20, verbose_name='\u0442\u0435\u043b\u0435\u0444\u043e\u043d 1')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='\u0442\u0435\u043b\u0435\u0444\u043e\u043d 2')),
                ('copyright', models.CharField(blank=True, max_length=255, verbose_name='copyright')),
            ],
            options={
                'verbose_name': '\u043d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u0441\u0430\u0439\u0442\u0430',
                'verbose_name_plural': '\u043d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u0441\u0430\u0439\u0442\u0430',
            },
        ),
    ]
