# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u0430\u0434\u0440\u0435\u0441'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='email'),
        ),
    ]
