# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0002_auto_20161218_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='plan_file1',
            field=models.FileField(blank=True, null=True, upload_to=b'sitesettings', verbose_name='\u0423\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0438\u0435 \u043f\u0440\u043e\u0435\u043a\u0442\u0430 \u043f\u043b\u0430\u043d\u0438\u0440\u043e\u0432\u043a\u0438 \u0442\u0435\u0440\u0440\u0438\u0442\u043e\u0440\u0438\u0438 \u041a\u041f'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='plan_file2',
            field=models.FileField(blank=True, null=True, upload_to=b'sitesettings', verbose_name='\u041f\u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u0435 \u043e \u0440\u0430\u0437\u0440\u0430\u0431\u043e\u0442\u043a\u0435 \u043f\u0440\u043e\u0435\u043a\u0442\u0430 \u043f\u043b\u0430\u043d\u0438\u0440\u043e\u0432\u043a\u0438 \u0442\u0435\u0440\u0440\u0438\u0442\u043e\u0440\u0438\u0438 \u041a\u041f'),
        ),
    ]
