# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0003_auto_20161218_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='\u0442\u0435\u043a\u0441\u0442')),
                ('weight', models.PositiveIntegerField(default=100, verbose_name='\u0432\u0435\u0441')),
            ],
            options={
                'ordering': ['weight'],
                'verbose_name': '\u0444\u0440\u0430\u0437\u0430 \u0441\u043e\u0440\u043e\u043a\u0438',
                'verbose_name_plural': '\u0444\u0440\u0430\u0437\u044b \u0441\u043e\u0440\u043e\u043a\u0438',
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='men_text',
            field=models.TextField(default='Hello!', verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043c\u0443\u0436\u0447\u0438\u043d\u044b \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u043e\u0439'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birdtext',
            name='sitesettings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bird_texts', to='sitesettings.SiteSettings'),
        ),
    ]
