# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('content', tinymce.models.HTMLField(verbose_name='\u0441\u043e\u0434\u0435\u0440\u0436\u0438\u043c\u043e\u0435')),
            ],
            options={
                'verbose_name': '\u043e \u043f\u043e\u0441\u0435\u043b\u043a\u0435',
                'verbose_name_plural': '\u043e \u043f\u043e\u0441\u0435\u043b\u043a\u0435',
            },
        ),
    ]
