# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='\u0424\u0418\u041e')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='\u0442\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': '\u0437\u0430\u044f\u0432\u043a\u0430 \u0431\u0440\u043e\u043d\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f \u0443\u0447\u0430\u0441\u0442\u043a\u0430',
                'verbose_name_plural': '\u0437\u0430\u044f\u0432\u043a\u0438 \u0431\u0440\u043e\u043d\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f \u0443\u0447\u0430\u0441\u0442\u043a\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.PositiveIntegerField(choices=[(1, '\u043f\u0435\u0440\u0432\u0430\u044f'), (2, '\u0432\u0442\u043e\u0440\u0430\u044f')], unique=True, verbose_name='\u043d\u043e\u043c\u0435\u0440 \u043e\u0447\u0435\u0440\u0435\u0434\u0438')),
                ('title', models.CharField(max_length=255, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name='\u0441\u043e\u0434\u0435\u0440\u0436\u0438\u043c\u043e\u0435')),
            ],
            options={
                'verbose_name': '\u043e\u0447\u0435\u0440\u0435\u0434\u044c \u0441\u0442\u0440\u043e\u0438\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u0430',
            },
        ),
        migrations.CreateModel(
            name='Stead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(0, '\u0441\u0432\u043e\u0431\u043e\u0434\u0435\u043d'), (1, '\u0437\u0430\u0431\u0440\u043e\u043d\u0438\u0440\u043e\u0432\u0430\u043d'), (2, '\u043f\u0440\u043e\u0434\u0430\u043d')], default=0)),
                ('title', models.CharField(max_length=255, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('image', models.ImageField(upload_to=b'plan', verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('area', models.CharField(max_length=255, verbose_name='\u043f\u043b\u043e\u0449\u0430\u0434\u044c \u0443\u0447\u0430\u0441\u0442\u043a\u0430')),
                ('price', models.CharField(max_length=255, verbose_name='\u0446\u0435\u043d\u0430')),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name='\u0441\u043e\u0434\u0435\u0440\u0436\u0438\u043c\u043e\u0435')),
                ('id_stead', models.CharField(max_length=10, unique=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Queue', verbose_name=b'\xd0\xbe\xd1\x87\xd0\xb5\xd1\x80\xd0\xb5\xd0\xb4\xd1\x8c')),
            ],
            options={
                'verbose_name': '\u0443\u0447\u0430\u0441\u0442\u043e\u043a',
                'verbose_name_plural': '\u0443\u0447\u0430\u0441\u0442\u043a\u0438',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='stead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Stead', verbose_name='\u0443\u0447\u0430\u0441\u0442\u043e\u043a'),
        ),
    ]
