# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_queue_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='stead',
            name='number',
            field=models.PositiveIntegerField(null=True, verbose_name='\u043d\u043e\u043c\u0435\u0440 \u0443\u0447\u0430\u0441\u0442\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='stead',
            name='image',
            field=models.ImageField(null=True, upload_to=b'plan', verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
