# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20161218_0158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'verbose_name': '\u043e\u0447\u0435\u0440\u0435\u0434\u044c \u0441\u0442\u0440\u043e\u0438\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u0430', 'verbose_name_plural': '\u043e\u0447\u0435\u0440\u0435\u0434\u0438 \u0441\u0442\u0440\u043e\u0438\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u0430'},
        ),
    ]
