# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20161218_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='text',
            field=models.TextField(blank=True, verbose_name='\u0442\u0435\u043a\u0441\u0442 \u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u044f'),
        ),
    ]
