# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_order_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stead',
            name='area',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u043f\u043b\u043e\u0449\u0430\u0434\u044c \u0443\u0447\u0430\u0441\u0442\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='stead',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'plan', verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='stead',
            name='price',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u0446\u0435\u043d\u0430'),
        ),
    ]
