# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_auto_20170201_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteadDocFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430')),
                ('file', models.FileField(upload_to=b'plan', verbose_name='\u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_files', to='plan.Stead', verbose_name='\u0443\u0447\u0430\u0441\u0442\u043e\u043a')),
            ],
            options={
                'verbose_name': '\u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442',
                'verbose_name_plural': '\u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b \u0441\u043e\u0431\u0441\u0442\u0432\u0435\u043d\u0438\u043a\u0430',
            },
        ),
    ]
