# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileBrowserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[(b'img', '\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'), (b'doc', 'Document')], max_length=3)),
                ('uploaded_file', models.FileField(upload_to=b'mce_filebrowser/%Y/%m/%d', verbose_name='File / Image')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
            ],
        ),
    ]
